[tool.poetry]
name = "scenic"
version = "2.0.0"
description = "The Scenic scenario description language."
authors = [
	"Daniel Fremont <dfremont@ucsc.edu>",
	"Edward Kim",
	"Tommaso Dreossi",
	"Shromona Ghosh",
	"Xiangyu Yue",
	"Alberto L. Sangiovanni-Vincentelli",
	"Sanjit A. Seshia"
]
maintainers = ["Daniel Fremont <dfremont@ucsc.edu>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/BerkeleyLearnVerify/Scenic"
documentation = "https://scenic-lang.readthedocs.io"
classifiers = [
	'Operating System :: OS Independent',
	'Development Status :: 5 - Production/Stable',
]

[tool.poetry.dependencies]
python = "^3.7"
dotmap = "^1.3.13"
shapely = "^1.7.0"
mapbox_earcut = "^0.12.10"
matplotlib = "^3.2.1"
scipy = "*"
antlr4-python3-runtime = "~4.8"
numpy = "^1.18.2"
pynverse = "^0.1.4"
attrs = "^19.3.0"
wrapt = "^1.12.1"
gym = "^0.21.0"

pyproj = {version = "^2.6.0", optional = true}

pytest-randomly = {version = "^3.2.1", optional = true}
pytest = {version = "^6.0.0", optional = true}
sphinx = {version = "^3.1.0", optional = true}
tox = {version = "^3.14.0", optional = true}
sphinx_rtd_theme = {version = "^0.4.3", optional = true}
astor = {version = "^0.8.1", optional = true}
tqdm = "*"
# tensorflow = "^1.15.0"

# gfootball = "^2.10.1"
importlib = "^1.0.4"
dm-sonnet = "^1"
psutil = "^5.8.0"
# baselines = {git = "https://github.com/openai/baselines.git", rev = "master"}

[tool.poetry.extras]
guideways = ["pyproj"]
dev = [
	"pytest-randomly",
	"pytest",
	"sphinx",
	"sphinx_rtd_theme",
	"tox",
	"pygments",
	"astor",
	"pyproj",	# for running guideways modules
]

[tool.poetry.scripts]
scenic = 'scenic.__main__:dummy'

[tool.poetry.plugins."pygments.lexers"]
scenic = "scenic.syntax.pygment:ScenicLexer"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
